---
- name: umount part
  ansible.posix.mount:
    path: '{{ mountpoint }}'
    state: unmounted

  
- name: umount part
  ansible.posix.mount:
    path: '{{ mountpoint }}'
    state: absent_from_fstab
